=== andrea-ivanov/LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">
	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="numero" />
				<xs:element ref="longitud" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempo" />
				<xs:element ref="velocidadMedia" />
				<xs:element ref="desnivel" />
				<xs:element ref="salida" />
				<xs:element ref="llegada" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="galeriaSonidos" />
				<xs:element ref="coordenadasSalida" />
				<xs:element ref="coordenadasLlegada" />
				<xs:element ref="hitosImportantes" />
				<xs:element ref="puntosAnonimos" />
				<xs:element ref="clasificacionEtapa" />
				<xs:element ref="clasificacionGeneral" />
				<xs:element ref="clasificacionEquipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="numero">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1" />
				<xs:maxInclusive value="21" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="tiempo" type="xs:time" />
	<xs:element name="velocidadMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="salida" type="xs:string" />
	<xs:element name="llegada" type="xs:string" />
	<xs:element name="tipo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="valor" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="llana" />
								<xs:enumeration value="montana" />
								<xs:enumeration value="contrarreloj_individual" />
								<xs:enumeration value="contrarreloj_por_equipos" />
								<xs:enumeration value="media_montana" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="ruta" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="ruta" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaSonidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="sonido" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sonido">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="ruta" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadasSalida">
		<xs:complexType>
			<xs:attribute name="longitud" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="-180.0" />
						<xs:maxInclusive value="180.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="longitudUnidad" type="xs:string" use="required" />
			<xs:attribute name="latitud" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="-90.0" />
						<xs:maxInclusive value="90.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="latitudUnidad" type="xs:string" use="required" />
			<xs:attribute name="altitud" type="xs:decimal" use="required" />
			<xs:attribute name="altitudUnidad" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadasLlegada">
		<xs:complexType>
			<xs:attribute name="longitud" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="-180.0" />
						<xs:maxInclusive value="180.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="longitudUnidad" type="xs:string" use="required" />
			<xs:attribute name="latitud" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="-90.0" />
						<xs:maxInclusive value="90.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="latitudUnidad" type="xs:string" use="required" />
			<xs:attribute name="altitud" type="xs:decimal" use="required" />
			<xs:attribute name="altitudUnidad" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="hitosImportantes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puerto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="sprintIntermedio" />
				<xs:element minOccurs="0" maxOccurs="1" ref="sprintBonificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puerto">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombre" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="primera" />
						<xs:enumeration value="segunda" />
						<xs:enumeration value="tercera" />
						<xs:enumeration value="especial" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprintIntermedio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprintBonificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:attribute name="longitud" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="-180.0" />
						<xs:maxInclusive value="180.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="longitudUnidad" type="xs:string" use="required" />
			<xs:attribute name="latitud" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="-90.0" />
						<xs:maxInclusive value="90.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="latitudUnidad" type="xs:string" use="required" />
			<xs:attribute name="altitud" type="xs:decimal" use="required" />
			<xs:attribute name="altitudUnidad" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntosAnonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puntoAnonimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoAnonimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombre" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacionEtapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tiempo" type="xs:duration" />
			<xs:attribute name="diferencia" type="xs:duration" />
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacionGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificadoGeneral" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificadoGeneral">
		<xs:complexType>
			<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tiempo" type="xs:duration" />
			<xs:attribute name="diferencia" type="xs:duration" />
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacionEquipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="equipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipo">
		<xs:complexType>
			<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tiempo" type="xs:duration" />
			<xs:attribute name="diferencia" type="xs:duration" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== andrea-ivanov/LaVuelta2026/xml/etapaEsquema.xml
<?xml version='1.0' encoding='utf-8'?>
<etapa xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    <nombre>ALCOSSEBRE-CASTELLÓ</nombre>
    <numero>6</numero>
    <longitud unidad="km">195.4</longitud>
    <fecha>2026-09-12</fecha>
    <tiempo>00:00:00</tiempo>
    <velocidadMedia unidad="km/h">0</velocidadMedia>
    <desnivel unidad="m">3094</desnivel>
    <salida>ALCOSSEBRE</salida>
    <llegada>CASTELLÓ</llegada>
    <tipo valor="media_montana">Media montaña</tipo>
    <referencias>
        <referencia id="1">Ayuntamiento de Alcossebre. https://www.alcaladexivert.es/</referencia>
        <referencia id="2">Ayuntamiento de Castelló de la Plana. https://www.castello.es/es/</referencia>
        <referencia id="3">Generalitat Valenciana.
            https://parquesnaturales.gva.es/es/web/pn-serra-d-irta</referencia>
        <referencia id="4">Santa María de Castelló. https://www.concatedral.com/</referencia>
    </referencias>
    <galeriaFotos>
        <foto ruta="multimedia/salida.png">Salida de Alcossebre</foto>
        <foto ruta="multimedia/meta.jpg">Meta en Castelló</foto>
    </galeriaFotos>
    <galeriaVideos>
        <video ruta="multimedia/etapa-6-castello.mp4">Recorrido de la etapa</video>
    </galeriaVideos>
    <galeriaSonidos>
        <sonido ruta="multimedia/podcast_alcossebre.mp3">Podcast de Alcossebre</sonido>
    </galeriaSonidos>
    <coordenadasSalida longitud="0.246447" longitudUnidad="grados" latitud="40.252003" latitudUnidad="grados" altitud="15" altitudUnidad="m" />
    <coordenadasLlegada longitud="-0.033494" longitudUnidad="grados" latitud="39.975814" latitudUnidad="grados" altitud="19.99" altitudUnidad="m" />
    <hitosImportantes>
        <puerto tipo="segunda">
            <nombre>Puerto de la Serratella</nombre>
            <coordenadas longitud="0.028365" longitudUnidad="grados" latitud="40.323884" latitudUnidad="grados" altitud="838.4" altitudUnidad="m" />
            <distancia unidad="km">44.8</distancia>
        </puerto>
        <puerto tipo="tercera">
            <nombre>Coll de la Bandereta</nombre>
            <coordenadas longitud="-0.032645" longitudUnidad="grados" latitud="40.276616" latitudUnidad="grados" altitud="780.9" altitudUnidad="m" />
            <distancia unidad="km">66.1</distancia>
        </puerto>
        <puerto tipo="segunda">
            <nombre>Alto del Desierto de las Palmas</nombre>
            <coordenadas longitud="0.027091" longitudUnidad="grados" latitud="40.073811" latitudUnidad="grados" altitud="419.2" altitudUnidad="m" />
            <distancia unidad="km">128.6</distancia>
        </puerto>
        <sprintIntermedio>
            <coordenadas longitud="-0.007070" longitudUnidad="grados" latitud="40.025169" latitudUnidad="grados" altitud="23.0" altitudUnidad="m" />
            <distancia unidad="km">137.3</distancia>
        </sprintIntermedio>
        <puerto tipo="primera">
            <nombre>Puerto El Bartolo (Bonificado)</nombre>
            <coordenadas longitud="0.031343" longitudUnidad="grados" latitud="40.085827" latitudUnidad="grados" altitud="692.7" altitudUnidad="m" />
            <distancia unidad="km">156.4</distancia>
        </puerto>
        <puerto tipo="segunda">
            <nombre>Alto del Desierto de las Palmas</nombre>
            <coordenadas longitud="0.027091" longitudUnidad="grados" latitud="40.073811" latitudUnidad="grados" altitud="419.2" altitudUnidad="m" />
            <distancia unidad="km">160.0</distancia>
        </puerto>
    </hitosImportantes>
    <puntosAnonimos>
        <puntoAnonimo>
            <nombre>Punto anonimo 1</nombre>
            <coordenadas longitud="0.239624" longitudUnidad="grados" latitud="40.272247" latitudUnidad="grados" altitud="103.9" altitudUnidad="m" />
            <distancia unidad="km">2.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 2</nombre>
            <coordenadas longitud="0.224780" longitudUnidad="grados" latitud="40.282785" latitudUnidad="grados" altitud="159.5" altitudUnidad="m" />
            <distancia unidad="km">4.1</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 3</nombre>
            <coordenadas longitud="0.227671" longitudUnidad="grados" latitud="40.299101" latitudUnidad="grados" altitud="149.5" altitudUnidad="m" />
            <distancia unidad="km">6.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 4</nombre>
            <coordenadas longitud="0.225222" longitudUnidad="grados" latitud="40.301381" latitudUnidad="grados" altitud="150.0" altitudUnidad="m" />
            <distancia unidad="km">6.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 5</nombre>
            <coordenadas longitud="0.229268" longitudUnidad="grados" latitud="40.306103" latitudUnidad="grados" altitud="152.1" altitudUnidad="m" />
            <distancia unidad="km">7.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 5</nombre>
            <coordenadas longitud="0.223058" longitudUnidad="grados" latitud="40.305096" latitudUnidad="grados" altitud="159.4" altitudUnidad="m" />
            <distancia unidad="km">7.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 6</nombre>
            <coordenadas longitud="0.218108" longitudUnidad="grados" latitud="40.302959" latitudUnidad="grados" altitud="167.7" altitudUnidad="m" />
            <distancia unidad="km">8.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 7</nombre>
            <coordenadas longitud="0.189485" longitudUnidad="grados" latitud="40.301643" latitudUnidad="grados" altitud="258.2" altitudUnidad="m" />
            <distancia unidad="km">10.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 8</nombre>
            <coordenadas longitud="0.181940" longitudUnidad="grados" latitud="40.292409" latitudUnidad="grados" altitud="294.1" altitudUnidad="m" />
            <distancia unidad="km">11.8</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 9</nombre>
            <coordenadas longitud="0.179285" longitudUnidad="grados" latitud="40.295793" latitudUnidad="grados" altitud="297.2" altitudUnidad="m" />
            <distancia unidad="km">12.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 11</nombre>
            <coordenadas longitud="0.171842" longitudUnidad="grados" latitud="40.295744" latitudUnidad="grados" altitud="226.3" altitudUnidad="m" />
            <distancia unidad="km">12.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 10</nombre>
            <coordenadas longitud="0.170660" longitudUnidad="grados" latitud="40.298292" latitudUnidad="grados" altitud="236.2" altitudUnidad="m" />
            <distancia unidad="km">13.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 12</nombre>
            <coordenadas longitud="0.164383" longitudUnidad="grados" latitud="40.295482" latitudUnidad="grados" altitud="191.8" altitudUnidad="m" />
            <distancia unidad="km">14.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 13</nombre>
            <coordenadas longitud="0.132651" longitudUnidad="grados" latitud="40.320245" latitudUnidad="grados" altitud="235.2" altitudUnidad="m" />
            <distancia unidad="km">19.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 14</nombre>
            <coordenadas longitud="0.079587" longitudUnidad="grados" latitud="40.258657" latitudUnidad="grados" altitud="279.8" altitudUnidad="m" />
            <distancia unidad="km">29.2</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 15</nombre>
            <coordenadas longitud="0.038963" longitudUnidad="grados" latitud="40.271185" latitudUnidad="grados" altitud="428.6" altitudUnidad="m" />
            <distancia unidad="km">33.8</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 16</nombre>
            <coordenadas longitud="0.040295" longitudUnidad="grados" latitud="40.287581" latitudUnidad="grados" altitud="598.2" altitudUnidad="m" />
            <distancia unidad="km">37.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 17</nombre>
            <coordenadas longitud="0.030816" longitudUnidad="grados" latitud="40.288025" latitudUnidad="grados" altitud="718.2" altitudUnidad="m" />
            <distancia unidad="km">38.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 18</nombre>
            <coordenadas longitud="0.051153" longitudUnidad="grados" latitud="40.339364" latitudUnidad="grados" altitud="743.3" altitudUnidad="m" />
            <distancia unidad="km">48.1</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 19</nombre>
            <coordenadas longitud="0.023511" longitudUnidad="grados" latitud="40.356145" latitudUnidad="grados" altitud="527.0" altitudUnidad="m" />
            <distancia unidad="km">52.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Punto anonimo 20</nombre>
            <coordenadas longitud="-0.047145" longitudUnidad="grados" latitud="40.298596" latitudUnidad="grados" altitud="473.5" altitudUnidad="m" />
            <distancia unidad="km">61.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
