=== andrea-ivanov/LaVuelta2026/xml/etapa.dtd
<!ELEMENT etapa (nombre, numero, longitud, fecha, tiempo, velocidadMedia, desnivel, salida, llegada, tipo, referencias, galeriaFotos, galeriaVideos, galeriaSonidos, coordenadasSalida, coordenadasLlegada, hitosImportantes, puntosAnonimos, clasificacionEtapa, clasificacionGeneral, clasificacionEquipos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT velocidadMedia (#PCDATA)>
<!ATTLIST velocidadMedia unidad CDATA #REQUIRED>
<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel unidad CDATA #REQUIRED>
<!ELEMENT salida (#PCDATA)>
<!ELEMENT llegada (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ATTLIST tipo valor (llana|montana|contrarreloj_individual|contrarreloj_por_equipos|media_montana) #REQUIRED>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia id CDATA #REQUIRED>
<!ELEMENT galeriaFotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto ruta CDATA #REQUIRED>
<!ELEMENT galeriaVideos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video ruta CDATA #REQUIRED>
<!ELEMENT galeriaSonidos (sonido+)>
<!ELEMENT sonido (#PCDATA)>
<!ATTLIST sonido ruta CDATA #REQUIRED>
<!ELEMENT coordenadasSalida EMPTY>
<!ATTLIST coordenadasSalida
    longitud CDATA #REQUIRED
    longitudUnidad CDATA #REQUIRED
    latitud CDATA #REQUIRED
    latitudUnidad CDATA #REQUIRED
    altitud CDATA #REQUIRED
    altitudUnidad CDATA #REQUIRED>
<!ELEMENT coordenadasLlegada EMPTY>
<!ATTLIST coordenadasLlegada
    longitud CDATA #REQUIRED
    longitudUnidad CDATA #REQUIRED
    latitud CDATA #REQUIRED
    latitudUnidad CDATA #REQUIRED
    altitud CDATA #REQUIRED
    altitudUnidad CDATA #REQUIRED>
<!ELEMENT hitosImportantes (puerto | sprintIntermedio | sprintBonificado)+>
<!ELEMENT puerto (nombre?, coordenadas, distancia)>
<!ATTLIST puerto tipo (primera|segunda|tercera|especial|bonificado) #REQUIRED>
<!ELEMENT sprintIntermedio (coordenadas, distancia)>
<!ELEMENT sprintBonificado (coordenadas, distancia)>
<!ELEMENT coordenadas EMPTY>
<!ATTLIST coordenadas
    longitud CDATA #REQUIRED
    longitudUnidad CDATA #REQUIRED
    latitud CDATA #REQUIRED
    latitudUnidad CDATA #REQUIRED
    altitud CDATA #REQUIRED
    altitudUnidad CDATA #REQUIRED>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT puntosAnonimos (puntoAnonimo+)>
<!ELEMENT puntoAnonimo (nombre?, coordenadas, distancia)>
<!ELEMENT clasificacionEtapa (clasificado, clasificado, clasificado)>
<!ELEMENT clasificado EMPTY>
<!ATTLIST clasificado
    posicion CDATA #REQUIRED
    nombre CDATA #REQUIRED
    tiempo CDATA #IMPLIED
    diferencia CDATA #IMPLIED>
<!ELEMENT clasificacionGeneral (clasificadoGeneral, clasificadoGeneral, clasificadoGeneral)>
<!ELEMENT clasificadoGeneral EMPTY>
<!ATTLIST clasificadoGeneral
    posicion CDATA #REQUIRED
    nombre CDATA #REQUIRED
    tiempo CDATA #IMPLIED
    diferencia CDATA #IMPLIED>
<!ELEMENT clasificacionEquipos (equipo, equipo, equipo)>
<!ELEMENT equipo EMPTY>
<!ATTLIST equipo
    posicion CDATA #REQUIRED
    nombre CDATA #REQUIRED
    tiempo CDATA #IMPLIED
    diferencia CDATA #IMPLIED>

=== andrea-ivanov/LaVuelta2026/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">

<etapa>
    <nombre>ALCOSSEBRE-CASTELLÓ</nombre>
    <numero>6</numero>
    <longitud unidad="km">195.4</longitud>
    <fecha>2026-09-12</fecha>
    <tiempo>No definido</tiempo>
    <velocidadMedia unidad="km/h">No definido</velocidadMedia>
    <desnivel unidad="m">3094</desnivel>
    <salida>ALCOSSEBRE</salida>
    <llegada>CASTELLÓ</llegada>
    <tipo valor="media_montana">Media montaña</tipo>

    <referencias>
        <referencia id="1">Ayuntamiento de Alcossebre. https://www.alcaladexivert.es/</referencia>
        <referencia id="2">Ayuntamiento de Castelló de la Plana. https://www.castello.es/es/</referencia>
        <referencia id="3">Generalitat Valenciana.
            https://parquesnaturales.gva.es/es/web/pn-serra-d-irta</referencia>
        <referencia id="4">Santa María de Castelló. https://www.concatedral.com/</referencia>
    </referencias>

    <galeriaFotos>
        <foto ruta="multimedia/salida.png">Salida de Alcossebre</foto>
        <foto ruta="multimedia/meta.jpg">Meta en Castelló</foto>
    </galeriaFotos>

    <galeriaVideos>
        <video ruta="multimedia/etapa-6-castello.mp4">Recorrido de la etapa</video>
    </galeriaVideos>

    <galeriaSonidos>
        <sonido ruta="multimedia/podcast_alcossebre.mp3">Podcast de Alcossebre</sonido>
    </galeriaSonidos>

    <coordenadasSalida longitud="0.246447" longitudUnidad="grados" latitud="40.252003"
        latitudUnidad="grados" altitud="15" altitudUnidad="m" />
    <coordenadasLlegada longitud="-0.033494" longitudUnidad="grados" latitud="39.975814"
        latitudUnidad="grados" altitud="19,99" altitudUnidad="m" />

    <hitosImportantes>
        <puerto tipo="segunda">
            <nombre>Puerto de la Serratella</nombre>
            <coordenadas longitud="0.0248" longitudUnidad="grados" latitud="40.3015"
                latitudUnidad="grados" altitud="839" altitudUnidad="m" />
            <distancia unidad="km">44.6</distancia>
        </puerto>
        <puerto tipo="tercera">
            <nombre>Coll de la Bandereta</nombre>
            <coordenadas longitud="0.0673" longitudUnidad="grados" latitud="40.2443"
                latitudUnidad="grados" altitud="790" altitudUnidad="m" />
            <distancia unidad="km">66.1</distancia>
        </puerto>
        <puerto tipo="segunda">
            <nombre>Alto del Desierto de las Palmas</nombre>
            <coordenadas longitud="0.0354" longitudUnidad="grados" latitud="40.0768"
                latitudUnidad="grados" altitud="422" altitudUnidad="m" />
            <distancia unidad="km">128.5</distancia>
        </puerto>
        <puerto tipo="primera">
            <nombre>Puerto El Bartolo</nombre>
            <coordenadas longitud="0.0298" longitudUnidad="grados" latitud="40.0886"
                latitudUnidad="grados" altitud="713" altitudUnidad="m" />
            <distancia unidad="km">156.8</distancia>
        </puerto>
        <sprintIntermedio>
            <coordenadas longitud="0.0631" longitudUnidad="grados" latitud="40.0531"
                latitudUnidad="grados" altitud="14" altitudUnidad="m" />
            <distancia unidad="km">120.1</distancia>
        </sprintIntermedio>
    </hitosImportantes>

    <puntosAnonimos>
        <puntoAnonimo>
            <coordenadas longitud="0.246426" longitudUnidad="grados" latitud="40.252016"
                latitudUnidad="grados" altitud="59.9" altitudUnidad="m" />
            <distancia unidad="km">0.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.231971" longitudUnidad="grados" latitud="40.275546"
                latitudUnidad="grados" altitud="128.5" altitudUnidad="m" />
            <distancia unidad="km">4.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.226871" longitudUnidad="grados" latitud="40.297389"
                latitudUnidad="grados" altitud="148.3" altitudUnidad="m" />
            <distancia unidad="km">8.1</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.186668" longitudUnidad="grados" latitud="40.297667"
                latitudUnidad="grados" altitud="255.4" altitudUnidad="m" />
            <distancia unidad="km">15.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.169888" longitudUnidad="grados" latitud="40.297216"
                latitudUnidad="grados" altitud="224.4" altitudUnidad="m" />
            <distancia unidad="km">18.2</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.143504" longitudUnidad="grados" latitud="40.31396"
                latitudUnidad="grados" altitud="270.7" altitudUnidad="m" />
            <distancia unidad="km">24.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.116348" longitudUnidad="grados" latitud="40.307645"
                latitudUnidad="grados" altitud="178.3" altitudUnidad="m" />
            <distancia unidad="km">29.8</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.077416" longitudUnidad="grados" latitud="40.262071"
                latitudUnidad="grados" altitud="267.3" altitudUnidad="m" />
            <distancia unidad="km">38.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.051414" longitudUnidad="grados" latitud="40.272711"
                latitudUnidad="grados" altitud="379.8" altitudUnidad="m" />
            <distancia unidad="km">46.1</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.03642" longitudUnidad="grados" latitud="40.275716"
                latitudUnidad="grados" altitud="474.5" altitudUnidad="m" />
            <distancia unidad="km">52.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.031015" longitudUnidad="grados" latitud="40.289816"
                latitudUnidad="grados" altitud="723" altitudUnidad="m" />
            <distancia unidad="km">58.7</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.030642" longitudUnidad="grados" latitud="40.305632"
                latitudUnidad="grados" altitud="803.2" altitudUnidad="m" />
            <distancia unidad="km">64.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.030029" longitudUnidad="grados" latitud="40.321"
                latitudUnidad="grados" altitud="823.1" altitudUnidad="m" />
            <distancia unidad="km">71.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.046086" longitudUnidad="grados" latitud="40.337798"
                latitudUnidad="grados" altitud="736.2" altitudUnidad="m" />
            <distancia unidad="km">80.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.046559" longitudUnidad="grados" latitud="40.35169"
                latitudUnidad="grados" altitud="624.3" altitudUnidad="m" />
            <distancia unidad="km">85.2</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="-0.01247" longitudUnidad="grados" latitud="40.33558"
                latitudUnidad="grados" altitud="541.8" altitudUnidad="m" />
            <distancia unidad="km">96.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="-0.042263" longitudUnidad="grados" latitud="40.296151"
                latitudUnidad="grados" altitud="506.8" altitudUnidad="m" />
            <distancia unidad="km">103.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="-0.021052" longitudUnidad="grados" latitud="40.275678"
                latitudUnidad="grados" altitud="726.1" altitudUnidad="m" />
            <distancia unidad="km">112.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="-0.006429" longitudUnidad="grados" latitud="40.258725"
                latitudUnidad="grados" altitud="670.1" altitudUnidad="m" />
            <distancia unidad="km">119.8</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.005361" longitudUnidad="grados" latitud="40.229619"
                latitudUnidad="grados" altitud="416.4" altitudUnidad="m" />
            <distancia unidad="km">125.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="-0.017073" longitudUnidad="grados" latitud="40.192529"
                latitudUnidad="grados" altitud="322.7" altitudUnidad="m" />
            <distancia unidad="km">132.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.014353" longitudUnidad="grados" latitud="40.165665"
                latitudUnidad="grados" altitud="270.5" altitudUnidad="m" />
            <distancia unidad="km">140.1</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.052832" longitudUnidad="grados" latitud="40.153321"
                latitudUnidad="grados" altitud="314.4" altitudUnidad="m" />
            <distancia unidad="km">148.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.090837" longitudUnidad="grados" latitud="40.144035"
                latitudUnidad="grados" altitud="193" altitudUnidad="m" />
            <distancia unidad="km">154.2</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <coordenadas longitud="0.148738" longitudUnidad="grados" latitud="40.138969"
                latitudUnidad="grados" altitud="10.4" altitudUnidad="m" />
